sudo: required

services:
  - docker

before_install:
  - docker build -t ibtisamurrahman/react-frontend  -f Dockerfile.dev .

script:
  - docker run ibtisamurrahman/react-frontend npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2',
  app: 'docker-react-frontend',
  env: 'Dockerreactfrontend-env',
  bucket_name: 'elasticbeanstalk-us-east-2-837565494443',
  bucket_path: 'docker-react-frontend'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"