sudo: required

services:
  - docker

before_install:
  - docker build -t ibtisamurrahman/react-frontend  -f Dockerfile.dev .

script:
  - docker run ibtisamurrahman/react-frontend npm run test -- --coverage